### ISSUE TITLE
MemoryFileSystem.isDirectory(r'\') crashes

### ISSUE THREAD

**Issue by aiurovet** [google/file.dart#198]
MemoryFileSystem.isDirectory() fails on r'\' and '/' when the style is FileSystemStyle.windows assuming the first two characters must represent drive letter and path separator.

**Comment by jamesderlin** [comment]
Using v6.1.4, I don't see a crash when using `MemoryFileSystem().isDirectory('')`, but it does return the wrong result (`true` instead of `false`, which is what `dart:io` or `LocalFileSystem` would return), regardless of the `FileSystemStyle`.

I do see an uncaught `RangeError` exception if using `/` with `FileSystemStyle.windows` from https://github.com/google/file.dart/blob/72a67c33f90bfb7e10057e286e06d2fe3baa4d98/packages/file/lib/src/backends/memory/memory_file_system.dart#L214-L216

The expectation is that `_context.isAbsolute(path)` logically implies that `path` includes `style.drive` as a prefix, which isn't true in this case.  Seems like the fix for that might be more appropriate for `package:path`, but I'm reluctant to touch that I'm not sure what changes are planned (or when) for v2.0 of that package.

**Comment by aiurovet** [comment]
OK, thank you.
