### ISSUE TITLE
Implement MemoryFileSystem.openSync()

### ISSUE THREAD

**Issue by tvolkert** [google/file.dart#7]
(and then enable the corresponding tests in `memory_test.dart`)

**Comment by bsutton** [comment]
I would like to put my vote behind this one as:

I'm trying to use the MemoryFileSystem to create a transient file system for unit tests that need to create/delete files and directories.

The package version is: 

file: ^5.1.0

I have created a class TestZone which uses IOOverride and I'm using the MemoryFileSystem as target for all IO overrides.

```dart
import 'dart:io';
import 'package:file/memory.dart';

class TestZone {
  MemoryFileSystem _fs;

  TestZone({
    FileSystemStyle style = FileSystemStyle.posix,
    MemoryFileSystem fileSystem,
  }) {
    if (fileSystem == null) {
      _fs = MemoryFileSystem(style: style);
    } else {
      _fs = fileSystem;
    }
  }

  void run<R>(R Function() body) {
    IOOverrides.runZoned(
      body,
      createDirectory: (String path) => _fs.directory(path),
      createFile: (String path) => _fs.file(path),
      createLink: (String path) => _fs.link(path),
      getCurrentDirectory: () => _fs.currentDirectory,
      setCurrentDirectory: (String path) => _fs.currentDirectory = path,
      getSystemTempDirectory: () => _fs.systemTempDirectory,
      stat: (String path) => _fs.stat(path),
      statSync: (String path) => _fs.statSync(path),
      fseIdentical: (String p1, String p2) => _fs.identical(p1, p2),
      fseIdenticalSync: (String p1, String p2) => _fs.identicalSync(p1, p2),
      fseGetType: (String path, bool followLinks) =>
          _fs.type(path, followLinks: followLinks),
      fseGetTypeSync: (String path, bool followLinks) =>
          typeSync(path, followLinks),
      fsWatch: (String a, int b, bool c) =>
          throw UnsupportedError('unsupported'),
      fsWatchIsSupported: () => _fs.isWatchSupported
    );
  }

  FileSystemEntityType typeSync(String path, bool followLinks) {
    path = path.substring(0, path.length - 1);

    return _fs.typeSync(path, followLinks: followLinks);
  }
}
```

The problem is that the MemoryFileSystem uses the class MemoryFile which does not have an implementation of openSync:

From the file memory_file.dart.

```dart
  @override
  io.RandomAccessFile openSync({io.FileMode mode = io.FileMode.read}) =>
      throw UnimplementedError('TODO');
```

This omission means that you can't just drop in a IOOverride and expect your code to work as normal.

I'm trying to implement a package that could be used by any developer that writes to the file system during unit tests and wants to protect their local file system from corruption.

This singular omission would appear to make this impossible.

**Comment by marcjoha** [comment]
Just adding a drive-by comment to signal interest.

Was hoping to use this library to speed up an image analysis component I'm working on.
